---

# DOCK
    
- name: Disable recent apps
  osx_defaults:
    domain: com.apple.dock
    key: 'show-recents'
    type: boolean
    value: false

- name: Enable {{ item.desc }}
  osx_defaults:
    domain: com.apple.dock
    key: '{{ item.key }}'
    type: boolean
    value: true
  loop:
    - key: magnification
      desc: 'Dock magnification'
    - key: showhidden
      desc: 'hidden app icon dimming'
    - key: autohide
      desc: 'Dock auto-hide'
    - key: static-only
      desc: 'only showing active apps in Dock'

- name: Set {{ item.desc }}
  osx_defaults:
    domain: com.apple.dock
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop:
    - key: orientation
      desc: 'Dock position'
      type: string
      value: bottom
    - key: tilesize
      desc: 'Dock normal size'
      type: integer
      value: 40
    - key: largesize
      desc: 'Dock magnified size'
      type: float
      value: 120
    - key: autohide-delay
      desc: 'Dock showing delay'
      type: float
      value: 0
    - key: autohide-time-modifier
      desc: 'Dock animation time'
      type: float
      value: 0
    - key: mineffect
      desc: 'windows minimizing effect'
      type: string
      value: suck

# MENU BAR

- name: Enable {{ item.desc }} in Menu Bar
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: '{{ item.key }}'
    type: boolean
    value: true
  loop:
    - key: Show24Hour
      desc: '24-hour clock'
    - key: FlashDateSeparators
      desc: 'time separators blinking'

- name: Set Menu Bar date format
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: 'EEE MMM d  H:mm'
    
- name: Hide {{ item.desc }} in Menu Bar
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: boolean
    value: false
  loop:
    - key: 'NSStatusItem Visible Item-0'
      desc: 'Text Input'
      domain: com.apple.TextInputMenuAgent
    - key: StatusMenuVisible
      desc: 'Siri'
      domain: com.apple.Siri

# CONTROL CENTER