---
- name: Enable {{ item.desc }}
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: boolean
    value: true
  loop:
    - key: AppleShowAllExtensions
      desc: 'showing all file extensions'
      domain: NSGlobalDomain
    - key: QuitMenuItem
      desc: "'Quit' option"
      domain: com.apple.finder
    - key: ShowExternalHardDrivesOnDesktop
      desc: "showing external hard drives on Desktop"
      domain: com.apple.finder
    - key: ShowRemovableMediaOnDesktop
      desc: 'showing removable media on Desktop'
      domain: com.apple.finder
    - key: _FXSortFoldersFirst
      desc: 'keeping folders on top'
      domain: com.apple.finder
    - key: _FXSortFoldersFirstOnDesktop
      desc: 'keeping folders on top on Desktop'
      domain: com.apple.finder
    - key: com.apple.springing.enabled
      desc: 'Spring-Loading'
      domain: NSGlobalDomain
    - key: DSDontWriteNetworkStores
      desc: 'no .DS_Store on network volumes'
      domain: com.apple.desktopservices

- name: Enable title bar icons in Finder
  become: true
  osx_defaults:
    domain: com.apple.universalaccess
    key: showWindowTitlebarIcons
    type: boolean
    value: true

- name: Disable {{ item.desc }}
  osx_defaults:
    domain: com.apple.finder
    key: '{{ item.key }}'
    type: boolean
    value: false
  loop:
    - key: ShowRecentTags
      desc: 'tags section from sidebar'
    - key: FXRemoveOldTrashItems
      desc: 'trash removal after 30 days'

- name: Set {{ item.desc }}
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop:
    - key: FXPreferredViewStyle
      desc: 'default finder windows view'
      domain: com.apple.finder
      type: string
      value: clmv
    - key: SidebarWidth
      desc: 'sidebar width'
      domain: com.apple.finder
      type: float
      value: 133
    - key: FXDefaultSearchScope
      desc: 'default search scope'
      domain: com.apple.finder
      type: string
      value: SCcf
    - key: NSToolbarTitleViewRolloverDelay
      desc: 'title bar rollover delay'
      domain: NSGlobalDomain
      type: float
      value: 0
    - key: NSTableViewDefaultSizeMode
      desc: 'size bar icon size'
      domain: NSGlobalDomain
      type: integer
      value: 2
    - key: com.apple.springing.delay
      desc: 'Spring-Loading delay'
      domain: NSGlobalDomain
      type: float
      value: 0.2