---
# Desktop

- name: Set {{ item.desc }}
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop:
    - key: AppleInterfaceStyle
      desc: 'system appearance'
      domain: NSGlobalDomain
      type: string
      value: Dark
    - key: AppleWindowTabbingMode
      desc: 'Prefer tabs to manual'
      domain: NSGlobalDomain
      type: string
      value: manual
    - key: AppleShowScrollBars
      desc: 'scroll bars to show when scrolling'
      domain: NSGlobalDomain
      type: string
      value: WhenScrolling
    - key: mouseDriverCursorSize
      desc: 'cursor size'
      domain: com.apple.universalaccess
      type: float
      value: 1.6
    
- name: Reduce motion
  osx_defaults:
    domain: com.apple.universalaccess
    key: reduceMotion
    type: boolean
    value: true
    
- name: Disable {{ item.desc }}
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: boolean
    value: false
  loop:
    - key: mru-spaces
      desc: 'automatic desktop rearrangement'
      domain: com.apple.dock
    - key: 'Assistant Enabled'
      desc: 'Siri'
      domain: com.apple.assistant.support
    - key: Autogather
      desc: 'feedback report submission'
      domain: com.apple.appleseed.FeedbackAssistant

# Screenshots
    
- name: Enable {{ item.desc }}
  osx_defaults:
    domain: com.apple.screencapture
    key: '{{ item.key }}'
    type: boolean
    value: true
  loop:
    - key: disable-shadow
      desc: 'spelling auto-correct'
    - key: include-date
      desc: 'date'
    - key: show-thumbnail
      desc: 'thumbnail'

# Input
    
- name: Disable {{ item.desc }}
  osx_defaults:
    domain: NSGlobalDomain
    key: '{{ item.key }}'
    type: boolean
    value: false
  loop:
    - key: NSAutomaticSpellingCorrectionEnabled
      desc: 'spelling auto-correct'
    - key: NSAutomaticCapitalizationEnabled
      desc: 'auto-cap'
    - key: NSAutomaticPeriodSubstitutionEnabled
      desc: 'period on double-space'