---
- name: Enable {{ item.desc }}
  osx_defaults:
    domain: '{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop:
    - key: com.apple.trackpad.forceClick
      desc: 'force click'
      domain: NSGlobalDomain
      type: boolean
      value: true
    - key: TrackpadThreeFingerDrag
      desc: 'three finger drag'
      domain: com.apple.AppleMultitouchTrackpad
      type: boolean
      value: true
    - key: TrackpadRightClick
      desc: 'right click'
      domain: com.apple.AppleMultitouchTrackpad
      type: boolean
      value: true
    - key: ActuateDetents
      desc: 'haptic feedback'
      domain: com.apple.AppleMultitouchTrackpad
      type: integer
      value: 1

- name: Set tracking speed
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.trackpad.scaling
    type: float
    value: 0.8

# Set feedback level - 0: Light, 1: Medium, 2: Firm

- name: Set {{ item.desc }}
  osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: '{{ item.key }}'
    type: integer
    value: '{{ item.value }}'
  loop:
    - key: FirstClickThreshold
      desc: 'first click feedback level'
      value: 0
    - key: SecondClickThreshold
      desc: 'second click feedback level'
      value: 0

# Enable key repeat

- name: Disable Press and Hold
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: boolean
    value: false

- name: Set {{ item.desc }}
  osx_defaults:
    domain: NSGlobalDomain
    key: '{{ item.key }}'
    type: integer
    value: '{{ item.value }}'
  loop:
    - key: InitialKeyRepeat
      desc: 'key repeat delay'
      value: 60
    - key: KeyRepeat
      desc: 'key repeat rate'
      value: 3