---
downloads: ./downloads
ansible_python_interpreter: python3

configure_dotfiles: true
configure_preferences: true
configure_apps: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
    - Launchpad
    - Mail
    - Maps
    - Messages
    - FaceTime
    - Reminders
    - TV
    - Podcasts
    - "App Store"
dockitems_persist:
    - name: "Finder"
      path: "/Applications/Finder.app/"
      pos: 1
    - name: "Safari"
      path: "/Applications/Safari.app/"
      pos: 2
    - name: "Calendar"
      path: "/Applications/Calendar.app/"
      pos: 3
    - name: "Music"
      path: "/Applications/Music.app/"
      pos: 4
    - name: "Notes"
      path: "/Applications/Notes.app/"
      pos: 5
    - name: "iTerm"
      path: "/Applications/iTerm.app/"
      pos: 6
    - name: "Visual Studio Code"
      path: "/Applications/Visual Studio Code.app/"
      pos: 7
    - name: "System Preferences"
      path: "/Applications/System Preferences.app/"
      pos: 8

homebrew_installed_packages:
    # - ansible # Installed via Pip.
    - git
    - go
    - nvm
    - jenv
    - zsh
    - jq
    - htop
    - vcpkg
    - maven
    - gradle
    - openjdk@8
    - awscli
    - openvpn
    - openssl
    - telnet
    - sqlite
    - spoof-mac

homebrew_taps:
    - homebrew/core
    - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
    - docker
    - firefox
    - google-chrome
    - visual-studio-code
    - intellij-idea
    - iterm2
    - discord
    - slack
    - zoom
    - prusaslicer
    - vlc
    - adguard
    - fanny
    - insomnia
    - google-drive
    - parallels
    - pd-runner
    - xquartz
    - vnc-viewer
    - ngrok

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_password: ""
mas_uninstalled_apps:
    - { id: 408981434, name: "iMovie" }
    - { id: 409183694, name: "Keynote" }
    - { id: 409201541, name: "Pages" }
    - { id: 409203825, name: "Numbers" }
    - { id: 682658836, name: "GarageBand" }
mas_installed_apps:
    - { id: 905953485, name: "NordVPN" }
    - { id: 360593530, name: "Notability" }
    - { id: 1444383602, name: "GoodNotes" }
    - { id: 1546729687, name: "Auto HD FPS for YouTube" }
    - { id: 1480933944, name: "Vimari" }
    - { id: 425424353, name: "The Unarchiver" }
    - { id: 497799835, name: "Xcode" }
