---
- hosts: all

  vars_files:
      - config.yml

  roles:
      - role: geerlingguy.mac.homebrew
        tags: ["homebrew"]
      - role: geerlingguy.mac.mas
        when: mas_installed_apps or mas_installed_app_ids
        tags: ["mas"]
      - role: geerlingguy.mac.dock
        when: configure_dock
        tags: ["dock"]

  tasks:
      - name: Set mac preferences.
        command: "./scripts/set-preferences.sh"
        when: configure_preferences
        tags: ["preferences"]

      - name: Create dotfile links.
        command: "./scripts/create-dotfile-links.sh"
        when: configure_dotfiles
        tags: ["dotfiles"]

      - name: Create plist links.
        command: "./scripts/create-plist-links.sh"
        when: configure_apps
        tags: ["apps"]

      - name: Link 'my-magic' omz custom theme.
        shell: ln -fs $(pwd)/custom/my-magic.zsh-theme ~/.oh-my-zsh/themes
        when: configure_apps
        tags: ["apps","custom"]
